### ISSUE TITLE
Loot vases don't drop loot and can't be broken

### ISSUE THREAD

**Issue by Zvzdov** [Pandarix/BetterArcheology#66]
Loot vases generated in structures for some reason don't drop any loot. When broken they drop a little bit of XP and reappear at the same spot. I tried to take a look in the log and found this:

```
at net.minecraft.class_2985.method_12884(class_2985.java:301) ~[client-intermediary.jar:?]
	at net.minecraft.class_2985.method_12882(class_2985.java:295) ~[client-intermediary.jar:?]
	at net.minecraft.class_2985.method_12878(class_2985.java:172) ~[client-intermediary.jar:?]
	at net.Pandarix.betterarcheology.block.custom.LootVaseBlock.method_9576(LootVaseBlock.java:41) ~[betterarcheology-1.1.6-1.20.1.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:255) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1083) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Pandarix** [comment]
Hi, sorry for the inconvenience!
There seems to be an issue with `LootVaseBlock.method_9576` which is the `onBreak` method.
If the log is precise (which in many cases could not be true, but for now let's say it is), granting the advancement for breaking a Loot Vase should be the problem.

Could you provide me with a little more context?
It seems that you are using BetterArcheology 1.1.6 for Minecraft 1.20.1. Is that correct? What other mods and loader are you using?

**Comment by Zvzdov** [comment]
Hi, thank you for the answer!

Yes, you are correct, I am using 1.1.6 for Minecraft 1.20.1 and fabric loader. I have datapack installed which has something to do with advancements including `loot_vase_broken`. I guess that is the cause of the problem.

upd: Yes I just fixed the issue by reverting changes to `loot_vase_broken` advancement. Sorry to bother!
